version: "3"

services:
  backend:
    image: tech-talks-backend:latest
    container_name: tt-back
    depends_on:
      - mongo
    volumes:
      - ./rest-api/src/:/usr/app/src/
    ports:
      - 3000:3000
    command: npm start

  frontend:
    image: nginx:1.13
    container_name: tt-front
    volumes:
      - ./web-app/:/usr/share/nginx/html/
    ports:
      - 8080:80

  mongo:
    image: mongo:4
    container_name: tt-mongodb
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123

  mongo-express:
    image: mongo-express
    container_name: tt-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: db-user
      ME_CONFIG_BASICAUTH_PASSWORD: mongo123
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
