version: "3"

services:
  backend:
    build: rest-api/.
    container_name: tt-back
    depends_on:
      - mongo
    volumes:
      - ./rest-api/src/:/usr/app/src/
    ports:
      - 3000:3000
    command: npm start

  frontend:
    image: nginx:1.13
    container_name: tt-front
    volumes:
      - ./web-app/:/usr/share/nginx/html/
    ports:
      - 80:80

  mongo:
    image: mongo:4
    container_name: tt-mongodb
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    container_name: tt-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo

  sonarqube:
    image: sonarqube:7.9-community
    container_name: tt-sonar
    ports:
      - 9000:9000