version: "3"

services:
  backend:
    image: tech-talks-backend:latest
    container_name: tt-back
    volumes:
      - ./src/:/usr/app/src/
    ports:
      - 3000:3000
    command: npm start
